site_name: BioExperiment Suite
repo_url: https://github.com/denis240997/bio_tools
repo_name: denis240997/bio_tools
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.path
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.top
    - toc.follow
    
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: blue grey
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: blue grey
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue grey
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

# Navigation structure
nav:
  - Getting Stared:
      - Installation: getting_started/installation.md
      - Quick Start: getting_started/quick_start.md
  - Examples:
      - Serial Connection: examples/serial_connection.md
      - Discover Devices: examples/discover_devices.md
      - Spectrophotometer: examples/spectrophotometer.md
      - Pump: examples/pump.md
      - Basic Experiment: examples/setting_up_experiment.md
      - Advanced Experiment: examples/advanced_experiment.md
  - API Reference:
      - Interfaces:
          - Serial Port: api/interfaces/serial_port.md
          - Spectrophotometer: api/interfaces/spectrophotometer.md
          - Pump: api/interfaces/pump.md
      - Tools: api/tools.md
      - Experiment:
          - Actions: api/experiment/actions.md
          - Experiment: api/experiment/experiment.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
