site_name: BioExperiment Suite
repo_url: https://github.com/denis240997/bio_tools
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.path
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.top
    - toc.follow
    
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: blue grey
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: blue grey
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue grey
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

# Navigation structure
nav:
  - Home: index.md
  - Experiment: experiment.md
  - Interfaces:
      - Overview: interfaces/index.md
      - Pump: interfaces/pump.md
      - Serial Connection: interfaces/serial_connection.md
      - Spectrophotometer: interfaces/spectrophotometer.md
  - Tools:
      - Overview: tools/index.md
      - Devices: tools/devices.md
      - Serial Port: tools/serial_port.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
